version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports: 
      - 3380:3380
      - 9229:9929
    volumes: 
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes: 
  pgdata:
    driver: local